### ISSUE TITLE
prototype injection was occured by TableView::_data

### ISSUE THREAD

**Issue by kjirou** [khirayama/hanson-front-end#4]
https://github.com/khirayama/handson-front-end/blob/master/src/intermediate/TableView.coffee#L2

``` coffee
class TableView
  _data: []
```

is compiled to:

``` js
function TableView() {}

TableView.prototype._data = [];
```

---

There is a possibility that such a problem occurs.

```
class Foo
  a: [1]

foo1 = new Foo
foo2 = new Foo

console.log foo1.a  # -> [ 1 ]
console.log foo2.a  # -> [ 1 ]

foo1.a.push 2
console.log foo1.a  # -> [ 1, 2 ]

console.log foo2.a  # -> [ 1, 2 ]
```

---

I think this definition is best.

``` coffee
class TableView
  constructor: ->
    @_data = [];
```

**Comment by khirayama** [comment]
Exactly, Well it does not...
But I think this is correct. What do you think?

``` coffeescript
class TableView
  _data = []
  constructor: ->
```

this script compile to this

``` javascript
TableView = (function() {
  var _data;

  function TableView() {}

  _data = [];

  return TableView;

})();
```

if this case, we keep _data is private.

**Comment by kjirou** [comment]
The `_data` is bound to `TableView` **statically**.
It means that you will share the value in **all instances**.

It is wrong as a class-based OOP.
Even if used, it will work only in the singleton-pattern class.

---

By the way, ES6's [Symbol](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Symbol)  will be answered in the `private property` issue.
For example, [in this way](https://github.com/kjirou/nodejs-codes/blob/master/examples/babel/Symbol/index.js).

**Comment by kjirou** [comment]
It was understood.
